export const ENDPOINTS = {
  SIGNIN: "/user/authenticate",
  FETCHALLEMPLOYEE: "/fetch/employee",
  FETCHCURRENTEMPLOYEE: "/fetch/employee/",
  SAVEEMPLOYEE: "/save/employee",
  UPDATEEMPLOYEE : "/update/employee",
  DELETEEMPLOYEE: "/delete/employee/",
  SAVEUSER: "/user/save",
  FETCHCURRENTUSER:"/fetch/userById/",
  FETCHALLUSERS: "/user/fetch/all",
  DELETEUSER: "/delete/user/",
  UPDATEUSER: "/update/user/",
  FETCHALLGROUPS: "/fetch/departments",
  SAVEGROUP: "/save/department",
  UPDATEGROUP: "/update/department",
  DELETEGROUP: "/delete/department/",
  FETCHEXPENSES: "/fetch/expenses",
  FETCHCURRENTEXPNESE:"/fetch/expenseById/",
  SAVEEXPENSE:"/save/expense",
  UPDATEEXPENSE:"/update/expense",
  DELETEEXPENSE:"/delete/expense/",
  FETCHTRIPS: "/fetch/trips",
  FETCHCURRENTTRIP:"/fetch/trip/",
  SAVETRIP:"/save/trip",
  UPDATETRIP:"/update/trip",
  DELETETRIP:"/delete/trip/",
  FETCHREPORTS: "/fetch/reports",
  FETCHCURRENTREPORT:"/fetch/report/",
  SAVEREPORT:"/save/report",
  UPDATEREPORT:"/update/report",
  DELETEREPORT:"/delete/report/",
  FETCHADVANCES:"/fetch/advances",
  FETCHCURRENTADVANCES:"/fetch/advance/",
  SAVEADVANCE:"/save/advance",
  UPDATEADVANCE:"/update/advance",
  DELETEADVANCE:"/delete/advance/",
  FETCHPAYMENTS: "/fetch/payments"
};
